-- ============================================
-- Sharingan Comics — Schema SQL
-- Base de datos: Oracle Autonomous (via Wallet)
-- Usuario: ADMIN
-- ============================================

-- Tabla principal de usuarios
CREATE TABLE USUARIOS (
    ID_USUARIO   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME     VARCHAR2(80)  NOT NULL UNIQUE,
    EMAIL        VARCHAR2(120) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    PHONE        VARCHAR2(30),
    ROLE         VARCHAR2(30)  DEFAULT 'CUSTOMER' NOT NULL,
    CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT   TIMESTAMP
);

-- Índices para búsquedas rápidas
CREATE INDEX IDX_USUARIOS_EMAIL    ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_USERNAME ON USUARIOS(USERNAME);

-- Comentarios de tabla
COMMENT ON TABLE  USUARIOS IS 'Usuarios registrados en Sharingan Comics';
COMMENT ON COLUMN USUARIOS.PASSWORD_HASH IS 'Hash BCrypt — nunca guardar contraseña plana';
COMMENT ON COLUMN USUARIOS.ROLE IS 'Roles: CUSTOMER, ADMIN';
