-- ============================================
-- Sharingan Comics — Schema SQL (versión con Clerk)
-- Base de datos: Oracle Autonomous (via Wallet)
-- Usuario: ADMIN
-- Versión: 2026-06 (integración Clerk + 2FA/MFA)
-- ============================================
-- NOTA: Este archivo refleja el estado OBJETIVO del esquema.
-- Para bases de datos ya inicializadas usar el script incremental:
--   database/migrations/2026_clerk_auth.sql
-- ============================================

-- Tabla principal de usuarios
-- Soporta usuarios locales (AUTH_PROVIDER='LOCAL') y Clerk (AUTH_PROVIDER='CLERK'/'GOOGLE')
CREATE TABLE USUARIOS (
    ID_USUARIO          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME            VARCHAR2(80)  NOT NULL UNIQUE,
    EMAIL               VARCHAR2(120) NOT NULL UNIQUE,

    -- Hash BCrypt. NULL para usuarios Clerk (minimización de datos, Ley 21.719 art. 3 lit. c)
    PASSWORD_HASH       VARCHAR2(255),

    PHONE               VARCHAR2(30),
    ROLE                VARCHAR2(30)  DEFAULT 'CUSTOMER' NOT NULL,

    -- ── Campos Clerk ────────────────────────────────────────────────
    -- Identificador Clerk (campo "sub" del JWT). NULL para usuarios locales.
    -- Índice único funcional en Oracle ignora NULLs correctamente.
    CLERK_USER_ID       VARCHAR2(150),

    -- Origen de autenticación: LOCAL | CLERK | GOOGLE
    -- Permite convivencia temporal durante migración progresiva.
    AUTH_PROVIDER       VARCHAR2(40)  DEFAULT 'LOCAL' NOT NULL,

    -- Indicador observacional de MFA. Fuente real: Clerk Dashboard/metadata.
    -- Cumple ISO 27001 A.9.4.2 (autenticación segura de sistema).
    MFA_ENABLED         NUMBER(1)     DEFAULT 0 NOT NULL,

    -- Trazabilidad de accesos. Cumple ISO 27001 A.12.4.1 y Ley 21.663.
    LAST_LOGIN_AT       TIMESTAMP,

    -- Aceptación de términos. Cumple Ley 21.719 (consentimiento).
    TERMS_ACCEPTED_AT   TIMESTAMP,
    PRIVACY_ACCEPTED_AT TIMESTAMP,
    -- ── Fin campos Clerk ────────────────────────────────────────────

    CREATED_AT          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP
);

-- Índices para búsquedas rápidas
CREATE INDEX IDX_USUARIOS_EMAIL         ON USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_USERNAME      ON USUARIOS(USERNAME);
CREATE INDEX IDX_USUARIOS_AUTH_PROVIDER ON USUARIOS(AUTH_PROVIDER);

-- Índice único para CLERK_USER_ID (NULL no genera duplicado en Oracle)
CREATE UNIQUE INDEX IDX_USUARIOS_CLERK_ID ON USUARIOS(CLERK_USER_ID);

-- Comentarios de tabla
COMMENT ON TABLE  USUARIOS IS 'Usuarios registrados en Sharingan Comics. Soporta auth local (JWT) y Clerk (2FA/MFA, Google).';
COMMENT ON COLUMN USUARIOS.PASSWORD_HASH  IS 'Hash BCrypt. NULL para usuarios Clerk. Nunca almacenar contraseña en texto plano.';
COMMENT ON COLUMN USUARIOS.ROLE           IS 'Roles internos: CUSTOMER, ADMIN. Fuente de verdad: Oracle (no el token frontend).';
COMMENT ON COLUMN USUARIOS.CLERK_USER_ID  IS 'ID Clerk (campo sub del JWT). Relaciona usuario interno con Clerk. NULL para locales.';
COMMENT ON COLUMN USUARIOS.AUTH_PROVIDER  IS 'Origen auth: LOCAL, CLERK, GOOGLE. Actualizado por UsuarioSyncService.';
COMMENT ON COLUMN USUARIOS.MFA_ENABLED    IS 'Indicador MFA (0=no, 1=sí). Fuente real: Clerk. Solo referencia local/auditoría.';
COMMENT ON COLUMN USUARIOS.LAST_LOGIN_AT  IS 'Timestamp último login exitoso. Auditoría ISO 27001 A.12.4.1 / Ley 21.663.';
COMMENT ON COLUMN USUARIOS.TERMS_ACCEPTED_AT    IS 'Consentimiento términos. Ley 21.719 art. 12.';
COMMENT ON COLUMN USUARIOS.PRIVACY_ACCEPTED_AT  IS 'Consentimiento privacidad. Ley 21.719.';

-- ============================================
-- Tablas de Pagos y Órdenes
-- ============================================

CREATE TABLE ORDENES (
    ID_ORDEN            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_USUARIO          NUMBER NOT NULL,
    EXTERNAL_REFERENCE  VARCHAR2(120) NOT NULL UNIQUE,
    BUYER_EMAIL         VARCHAR2(120) NOT NULL,
    TOTAL               NUMBER(12,2) NOT NULL,
    STATUS              VARCHAR2(40) DEFAULT 'CREATED' NOT NULL,
    MP_PREFERENCE_ID    VARCHAR2(120),
    MP_PAYMENT_ID       VARCHAR2(120),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT FK_ORDEN_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE ORDEN_ITEMS (
    ID_ITEM      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ORDEN     NUMBER NOT NULL,
    PRODUCT_CODE VARCHAR2(80) NOT NULL,
    TITLE        VARCHAR2(200) NOT NULL,
    DESCRIPTION  VARCHAR2(500),
    QUANTITY     NUMBER NOT NULL,
    UNIT_PRICE   NUMBER(12,2) NOT NULL,
    SUBTOTAL     NUMBER(12,2) NOT NULL,
    CONSTRAINT FK_ITEM_ORDEN FOREIGN KEY (ID_ORDEN)
        REFERENCES ORDENES(ID_ORDEN)
);

CREATE TABLE PAGOS_MP (
    ID_PAGO             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_ORDEN            NUMBER,
    MP_PAYMENT_ID       VARCHAR2(120),
    MP_STATUS           VARCHAR2(80),
    MP_STATUS_DETAIL    VARCHAR2(120),
    MP_PAYMENT_TYPE     VARCHAR2(80),
    RAW_NOTIFICATION    CLOB,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PAGO_ORDEN FOREIGN KEY (ID_ORDEN)
        REFERENCES ORDENES(ID_ORDEN)
);
